name 'cic_wordpress1'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cic_wordpress1'
long_description 'Installs/Configures cic_wordpress1'
version '0.1.0'
